@startuml
'https://plantuml.com/class-diagram

class Livre{

    private string $isbn;
    private string $titre;
    private DateTime $dateParution;
    private int $nbPages;
    private Auteur $auteur;

}


class Auteur{

    private int $id;
    private string $nomAuteur;
    private string $prenomAuteur;

}
@enduml