@startuml
'https://plantuml.com/class-diagram

:Utilisateur:
(searchByISBN)
(getAllLivre)
(getLivreByNomAuteur)

Utilisateur-->searchByISBN
Utilisateur-->getAllLivre
Utilisateur-->getLivreByNomAuteur

@enduml